# Generated by Django 4.2.1 on 2024-05-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, null=True, verbose_name="Отдел"),
                ),
            ],
            options={
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отделы",
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(null=True, verbose_name="Код")),
                (
                    "name",
                    models.CharField(max_length=200, null=True, verbose_name="Имя"),
                ),
                (
                    "department",
                    models.CharField(max_length=200, null=True, verbose_name="Отдел"),
                ),
            ],
            options={
                "verbose_name": "Сотрудники",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Вопрос"
                    ),
                ),
                (
                    "has_choices",
                    models.BooleanField(default=False, verbose_name="Есть варианты"),
                ),
                (
                    "option1",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Вариант 1"
                    ),
                ),
                (
                    "option2",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Вариант 2"
                    ),
                ),
                (
                    "option3",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Вариант 3"
                    ),
                ),
                (
                    "option4",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Вариант 4"
                    ),
                ),
                (
                    "option5",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Вариант 5"
                    ),
                ),
                ("option1_count", models.IntegerField(default=0)),
                ("option2_count", models.IntegerField(default=0)),
                ("option3_count", models.IntegerField(default=0)),
                ("option4_count", models.IntegerField(default=0)),
                ("option5_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
    ]
