# Generated by Django 4.2.1 on 2024-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_remove_questions_has_choices_questions_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="has_options",
            field=models.BooleanField(default=False, verbose_name="Есть варианты"),
        ),
    ]
