# Generated by Django 4.2.1 on 2023-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_message_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_text',
            field=models.TextField(verbose_name='Жалоба или предложение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Телефон'),
        ),
    ]
