# Generated by Django 4.2.1 on 2024-05-17 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_questions_has_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Ответ"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.employees",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ сотрудника",
                "verbose_name_plural": "Ответы сотрудников",
            },
        ),
    ]
