# Generated by Django 4.2.1 on 2024-05-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_employeeanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeanswer",
            name="employee_code",
            field=models.IntegerField(null=True, verbose_name="Код"),
        ),
        migrations.AddField(
            model_name="employeeanswer",
            name="is_complete",
            field=models.BooleanField(default=True, verbose_name="Завершен"),
        ),
    ]
