# Generated by Django 4.2.1 on 2024-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_employeeanswer_employee_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="option1_count",
            field=models.IntegerField(default=0, verbose_name="Количество варианта 1"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="option2_count",
            field=models.IntegerField(default=0, verbose_name="Количество варианта 2"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="option3_count",
            field=models.IntegerField(default=0, verbose_name="Количество варианта 3"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="option4_count",
            field=models.IntegerField(default=0, verbose_name="Количество варианта 4"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="option5_count",
            field=models.IntegerField(default=0, verbose_name="Количество варианта 5"),
        ),
        migrations.DeleteModel(
            name="EmployeeAnswer",
        ),
    ]
