# Generated by Django 4.2.1 on 2024-05-18 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_questions_option1_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.department",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ сотрудника",
                "verbose_name_plural": "Ответы сотрудников",
            },
        ),
    ]
