# Generated by Django 4.2.1 on 2024-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_alter_employeeresponse_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeresponse",
            name="response",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ответ"
            ),
        ),
    ]
