# Generated by Django 4.2.1 on 2024-05-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_alter_employeeresponse_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeresponse",
            name="question_text",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="employeeresponse",
            name="response",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ"),
        ),
    ]
