# Generated by Django 4.2.1 on 2024-05-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_employeeresponse_question_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Создан"
            ),
        ),
    ]
