# Generated by Django 4.2.1 on 2024-05-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_questions_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeresponse",
            name="question_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Вопрос в тексте"
            ),
        ),
    ]
