# Generated by Django 4.2.1 on 2024-05-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_alter_employeeresponse_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeresponse",
            name="response_option_no",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Вариант ответа"
            ),
        ),
        migrations.AlterField(
            model_name="employeeresponse",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="employeeresponse",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.department",
                verbose_name="Отдел",
            ),
        ),
        migrations.AlterField(
            model_name="employeeresponse",
            name="question_text",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос"),
        ),
    ]
