# Generated by Django 4.2.1 on 2024-05-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0015_employeeresponse_response_option_no_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeresponse",
            old_name="response_option_no",
            new_name="response_option",
        ),
    ]
