# Generated by Django 4.2.1 on 2024-06-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_response_option_no_employeeresponse_response_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отдел uz'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отдел ru'),
        ),
    ]
