# Generated by Django 4.2.1 on 2024-06-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_department_is_active_department_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeresponse',
            name='survey_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ID ответа'),
        ),
        migrations.CreateModel(
            name='SurveyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(blank=True, max_length=40, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department')),
            ],
            options={
                'unique_together': {('survey_id', 'department')},
            },
        ),
    ]
