# Generated by Django 4.2.1 on 2026-05-08 04:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_employeeresponse_survey_id_surveycompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Группа варианта',
                'verbose_name_plural': 'Группы вариантов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.TextField(blank=True, max_length=200, null=True, verbose_name='Вопрос uz')),
                ('question_ru', models.TextField(blank=True, max_length=200, null=True, verbose_name='Вопрос ru')),
                ('option_source', models.CharField(choices=[('manual', 'Manual'), ('department', 'Department')], default='manual', max_length=50)),
                ('question_type', models.CharField(blank=True, choices=[('text', 'Text'), ('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('number', 'Number')], max_length=50, null=True, verbose_name='Выбрать тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('is_required', models.BooleanField(blank=True, default=True, null=True, verbose_name='Обязательный')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст uz')),
                ('text_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ru')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='mainapp.optiongroup')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mainapp.question')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'ordering': ['question', 'group__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeresponse',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeresponse',
            name='question',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.AlterUniqueTogether(
            name='surveycompletion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='surveycompletion',
            name='department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.DeleteModel(
            name='EmployeeResponse',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='SurveyCompletion',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.questionoption'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.surveysubmission'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='mainapp_ans_questio_6417b2_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['selected_option'], name='mainapp_ans_selecte_89b990_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created_at'], name='mainapp_ans_created_2748d7_idx'),
        ),
    ]
