# Generated by Django 4.2.1 on 2026-05-11 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_foodcategory_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.menuitem'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('department', 'Department'), ('menu', 'Menu')], default='manual', max_length=50),
        ),
    ]
