# Generated by Django 4.2.1 on 2026-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_answer_menu_item_alter_question_option_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, related_name='questions', to='mainapp.foodcategory', verbose_name='Разрешенные категории'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_source',
            field=models.CharField(choices=[('manual', 'Вручную'), ('department', 'Отделы'), ('menu', 'Меню')], default='manual', max_length=50),
        ),
    ]
