# Generated by Django 4.2.1 on 2026-05-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_question_allowed_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_source',
            field=models.CharField(choices=[('manual', 'Вручную'), ('department', 'Отделы'), ('menu', 'Меню')], default='manual', max_length=50, verbose_name='Тип варианта'),
        ),
    ]
