# Generated by Django 4.2.1 on 2026-08-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_question_option_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Название_uz')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название_ru')),
                ('survey_type', models.CharField(choices=[('general', 'Умумий'), ('product', 'Янги маҳсулот')], default='general', max_length=30, verbose_name='Тип опроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='surveys/', verbose_name='Картинка')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание_uz')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание_ru')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='№ номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросники',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='№ номер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('number', 'Number')], max_length=50, null=True, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mainapp.survey', verbose_name='Сўровнома'),
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='mainapp.survey', verbose_name='Опрос тип'),
        ),
    ]
