# Generated by Django 4.2.1 on 2026-08-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_survey_alter_question_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['question', 'order'], 'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='group',
        ),
    ]
